# Generated by Django 5.1.6 on 2025-03-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.BooleanField(default=True)),
                ('simbolo', models.IntegerField(blank=True, null=True)),
                ('variacion', models.FloatField()),
                ('prob_exploracion', models.FloatField()),
                ('exploracion', models.BooleanField()),
                ('nombre', models.CharField(max_length=100)),
                ('movimientos', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Juego_Humano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador_primero', models.BooleanField(default=True)),
                ('vision', models.BooleanField(default=False)),
                ('rondas_jugadas', models.IntegerField(default=0)),
                ('rondas_max', models.IntegerField(default=2)),
                ('puntuacion', models.JSONField(default=list)),
                ('game_over', models.BooleanField(default=False)),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_1', to='Logica.agente')),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_2', to='Logica.agente')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.tablero')),
            ],
        ),
        migrations.CreateModel(
            name='Juego_Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.BooleanField(default=False)),
                ('victorias', models.JSONField(default=list)),
                ('rondas', models.IntegerField(default=10)),
                ('jugador_1_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_1_ia', to='Logica.agente')),
                ('jugador_2_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_2_ia', to='Logica.agente')),
                ('tablero_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.tablero')),
            ],
        ),
    ]
