# Generated by Django 5.1.6 on 2025-03-04 21:16

import Logica.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0003_alter_agente_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego_entrenamiento',
            name='tablero_ia',
            field=models.ForeignKey(default=Logica.models.Tablero_Unico, on_delete=django.db.models.deletion.CASCADE, to='Logica.tablero'),
        ),
        migrations.AlterField(
            model_name='juego_entrenamiento',
            name='victorias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='juego_humano',
            name='puntuacion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='juego_humano',
            name='tablero',
            field=models.ForeignKey(default=Logica.models.Tablero_Unico, on_delete=django.db.models.deletion.CASCADE, to='Logica.tablero'),
        ),
    ]
