# Generated by Django 5.1.6 on 2025-03-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0004_alter_juego_entrenamiento_tablero_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego_humano',
            name='ganador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='simbolo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='juego_entrenamiento',
            name='rondas',
            field=models.IntegerField(default=50),
        ),
    ]
