# Generated by Django 5.1.6 on 2025-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0005_juego_humano_ganador_alter_agente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego_humano',
            name='puntuacion',
            field=models.JSONField(blank=True, default=[0, 0, 0], null=True),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='estado',
            field=models.JSONField(default=[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
        ),
    ]
